name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build plugin (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          set -eux
          sudo apt-get update
          # Geany headers come from the 'geany' package on Debian/Ubuntu
          sudo apt-get install -y build-essential pkg-config geany libgtk-3-dev libcurl4-openssl-dev libjson-c-dev
          # Prefer GtkSourceView 3; if unavailable, use 4 and patch Makefile
          if sudo apt-get install -y libgtksourceview-3.0-dev ; then
            echo "GSV=3" >> $GITHUB_ENV
          else
            sudo apt-get install -y libgtksourceview-4-dev
            sed -i 's/gtksourceview-3.0/gtksourceview-4/g' Makefile || true
            echo "GSV=4" >> $GITHUB_ENV
          fi

      - name: Verify pkg-config modules
        run: |
          pkg-config --modversion geany
          pkg-config --cflags geany gtk+-3.0
          pkg-config --libs geany gtk+-3.0

      - name: Build
        run: |
          make
          file ai_chat.so || true
          ls -lh ai_chat.so || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ai_chat-${{ env.GSV }}-ubuntu
          path: ai_chat.so
